### ISSUE TITLE
MinConfidence Not Take Effect and NmsThresh Question

### ISSUE THREAD

**Issue by wolfwubo** [hsysfan/YOLOv5_Segmenation_implement#2]
Hello,
I test with several MinConfidence values, i.e. 0.2, 0.45, 0.9, 1.0. But return the same mask results. 
Also, it seems that when setting NmsThresh = 0.95 will make very same mask as predict.py with iou_thres=0.45( nms iou threshold).
Could you give me some comments. Thanks:)

**Comment by hsysfan** [comment]
I checked this error! 
This is my fault Sorry for interrupting your work!
I made another variable for confidence so i delete it and change my code now
Thank you for noticing this error!
https://github.com/hsysfan/YOLOv5_Segmenation_implement/blob/c49c33b3aeafca6e3580d433897e2272ea115602/OnnxSample/Yolov5/YoloDetector.cs#L156-L160

**Comment by wolfwubo** [comment]
Never mind, the code change does works! Appreciate your efforts for the change request. And what's the difference between NmsThresh in this project and iou_thres parameter in Python Yolov5?

**Comment by hsysfan** [comment]
I am not sure but i know CvDnn.NMSBoxes and torchvision.ops.nms are same function
Of course, it is not perfectly same
Anyway i think NmsThres and iou_thres are same thing
But C# function wants more arguments like conf_thres
It can make different result compared to pytorch yolov5
I think you should adjust this arguments

And please check this link
https://github.com/ultralytics/ultralytics/issues/284#issuecomment-1384146526
he said we can use CvDnn.NMSBoxes instead of torchvision.ops.nms 

Thanks you

**Comment by wolfwubo** [comment]
Got it, thanks a lot! I will do further studies on these parameters, if anything found, will let you see.
